30 sigabrt when closing a connection from client
TheSecretOrganization/ft_irc pull request #35
Opened 2024-06-17 14:55 UTC by Neffi42

- created deleteClient method
- delete client if connection is cut

2024-06-17 15:15 UTC, antoineverin requested changes

2024-06-17 15:15 UTC, antoineverin commented on src/Server.cpp
> +		std::find(clients.begin(), clients.end(), client);
not protected

2024-06-17 16:03 UTC, Neffi42 commented on src/Server.cpp
> +		std::find(clients.begin(), clients.end(), client);
ok corrected

2024-06-18 06:51 UTC, antoineverin approved these changes

2024-06-18 07:30 UTC, croueAlec approved these changes

2024-06-18 07:30 UTC, merged